feature/ANTIC-033 implemended statistics for all countries [SS, LB]
sw21-tug/Team_27 pull request #72
Opened 2021-05-19 14:51 UTC by scampiiTU13

2021-05-20 13:36 UTC, DinosaurierRex approved these changes
After discussion on how to write a test for this feature, this now looks good to me :+1:

2021-05-24 14:02 UTC, StanglTobias requested changes

2021-05-24 14:02 UTC, StanglTobias commented on AntiCovid/app/src/main/java/com/swtug/anticovid/view/statistics/StatisticFragment.kt
> +        update.text = R.string.statistic_error_message.toString()
`R.string.<ResourceName> ` returns an Integer. So your error message is a number. user `getString(R.string.<ResourceName>)` instead

2021-05-24 14:02 UTC, StanglTobias commented on AntiCovid/app/src/main/java/com/swtug/anticovid/view/statistics/StatisticFragment.kt
> +        update.text = format.format(date)
have a look at kotlin `with()` function

2021-05-26 13:04 UTC, closed without merging